### ISSUE TITLE
Align chance of winning input and slider

### ISSUE THREAD

**Issue by lgarest** [AndreMiras/etheroll#17]
Currently, when moving the **Chance of winning** slider, the value below it displays one number and the input displays another one.
[See the screenshot attached](https://i.imgur.com/Q65tB7h.png)

**Comment by AndreMiras** [comment]
Yep that's actually a feature. But I agree it's not obvious enough.
Basically one is the "roll under" and the other one gives you the "chances of winning".
If you want 50% chances to win, you need to roll *under* 51 (over 100).
Does it make sense?
I'll keep this ticket open until I come up with something more clear.

**Comment by lgarest** [comment]
ahahaha indeed, it makes sense!
