### ISSUE TITLE
Detect when MetaMask is installed but not logged in and prompt an error

### ISSUE THREAD

**Issue by Pi-Rr** [AndreMiras/etheroll#20]
Currently an error is prompted when people visit the site without MetaMask installed in their browser (related to #5 ).
An error should also be prompted when people have MetaMask installed but are not logged in: "You need to be logged in with MetaMask to use the site".

**Comment by AndreMiras** [comment]
I could sneak a fix over the weekend even though I was not supposed to geek 
![image](https://user-images.githubusercontent.com/24973/49338066-a0610f00-f61d-11e8-970e-c3151e569638.png)
