### ISSUE TITLE
Introduce react router for multiple games

### ISSUE THREAD

**Issue by AndreMiras** [AndreMiras/etheroll#30]
Build a draft router hierarchy for the other games, e.g. #11 
https://reacttraining.com/react-router/web/guides/quick-start

To begin with the idea would be to have a simple hierarchy that simply hold two different games: Etheroll and coin flip.

**Comment by lgarest** [comment]
I'll try to pick that up, or you want to do it yourself to learn react-router?

**Comment by AndreMiras** [comment]
Yes that would be awesome if you want to pick it up. But I prefer if you can keep it simple for now. So no fanciness so I can follow :smile:
